name: backend_drift
description: Backend en Dart con SQLite y Drift
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  drift: ^2.14.0
  sqlite3: ^2.3.0
  path: ^1.8.0
  logging: ^1.2.0

dev_dependencies:
  drift_dev: ^2.14.0
  build_runner: ^2.4.6
