name: backend_flutter
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  mysql1: ^0.20.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
